{
  "formatVersion": "1.1",
  "component": {
    "group": "ex.ss.lib",
    "module": "tools",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.0.5.aar",
          "url": "tools-1.0.5.aar",
          "size": 98262,
          "sha512": "47a9929d9a2886ef2167f0cbea4ba91a071c3bbe857cfbc5425ab15f5734fff02053e8265499d530746f0a552addf20138d14facf0fae7b859163dba8921fc01",
          "sha256": "acfa948aa6af92d18a615b3b54502df9415864427bd51af0e7a14a1ddd77604d",
          "sha1": "6dc5f70fa3a53ee8cdb1c0cd3657ae42ae4f6884",
          "md5": "368dc0c15732571cb4337f07ac06fbbb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.0.5.aar",
          "url": "tools-1.0.5.aar",
          "size": 98262,
          "sha512": "47a9929d9a2886ef2167f0cbea4ba91a071c3bbe857cfbc5425ab15f5734fff02053e8265499d530746f0a552addf20138d14facf0fae7b859163dba8921fc01",
          "sha256": "acfa948aa6af92d18a615b3b54502df9415864427bd51af0e7a14a1ddd77604d",
          "sha1": "6dc5f70fa3a53ee8cdb1c0cd3657ae42ae4f6884",
          "md5": "368dc0c15732571cb4337f07ac06fbbb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tools-1.0.5-sources.jar",
          "url": "tools-1.0.5-sources.jar",
          "size": 41063,
          "sha512": "8a4c8d3a8786424bf720b52d7bfd8ae915f628f620cf8efa5515db0f5dffd4f836ab85328b262e9578230b6f265e2b45d6c3d59feb1579af62ae2e8bdaaa119c",
          "sha256": "f660adfa87424aa3324577149505ef0ca3dcb4309c13b4e2c8e4a8241a924f4e",
          "sha1": "62f93105a69f8eab0489ce08042068897e7321ef",
          "md5": "cb8021e40adc11711f87d742a73ec260"
        }
      ]
    }
  ]
}
